/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Maq;

import DAO.daocfdi;
import Modelo.Conexiones;
import Modelo.Usuarios;
import Panelmaq.pagotpucargo1;
import Panelmaq.pagotpucargo2;
import Panelmaq.pagotpucargo3;
import Server.Serverylite;
import Tpu.Pagostpu;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author GATEWAY1-
 */
public class PagostpuCargos extends javax.swing.JInternalFrame {

    pagotpucargo1 c1;
    pagotpucargo2 c2;
    pagotpucargo3 c3;
    String var = "0";
    public String name, empresa, empresacob;
    Connection rcpt, litecfdi, liteempresa, cobranza, cpt, cobB;
    public Conexiones conexion;
    public Usuarios u;

    /**
     * Creates new form Clientes Hay que recordar que todos los registros estan
     * almacenados en la tabla fiscal de cargos especiales, por lo tanto no hay
     * que ingresar en el servidor interno para esta cuestion, se maneja por la
     * serie.
     *
     * @param cn
     * @param u
     */
    public PagostpuCargos(Conexiones cn, Usuarios u) {
        initComponents();
        cpt = cn.getCpttpu();
        rcpt = cn.getRcpttpu();
        cobranza = cn.getCobranzatpu();
        empresa = cn.getEmpresa();
        empresacob = cn.getEmpresacob();
        cobB = cn.getCobranzatpuB();
        litecfdi = cn.getLitecfdi();
        liteempresa = cn.getLiteempresa();
        this.u = u;
        conexiones();
        generaciontab();//Tabs de facturacion
        setarraylist();
    }

    private void conexiones() {//Conexiones a servidor
        try {
            Serverylite l = new Serverylite();
            litecfdi = l.getconexioncfdi();
            liteempresa = l.getconexionC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pagostpu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Pagostpu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pagostpu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setarraylist() {
        //tambien conexiones
        daocfdi d = new daocfdi();
        c1.empresa = empresa;
        c1.empresacob = empresacob;
        c1.ACobranza = cobranza;
        c1.sqlempresa = liteempresa;
        c1.sqlcfdi = litecfdi;
        c1.cpt = cpt;
        c1.u = u;

        //tambien conexiones
        c2.empresa = empresa;
        c2.ACobranza = cobranza;
        c2.cpt = cpt;
        c2.u = u;

        c3.empresa = empresa;
        c3.ACobranza = cobranza;
        c3.sqlempresa = liteempresa;
        c3.arrfpago = d.getFormadepago(litecfdi);
        c3.cpt = cpt;
        c3.u = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Tabbed = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Pagos Cargos especiales");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/labelprint.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Tabbed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            System.out.println("cerrar pagos");
            liteempresa.close();
            litecfdi.close();
        } catch (SQLException ex) {
            Logger.getLogger(PagostpuCargos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing
    public final void generaciontab() {//generar tabs
        c1 = new pagotpucargo1();
        c2 = new pagotpucargo2();
        c3 = new pagotpucargo3();
        Tabbed.addTab("Ver Pagos especiales", c1);
        Tabbed.addTab("Nuevo pago especial", c2);
        Tabbed.addTab("Complemento a pago ESPECIAL", c3);
        Tabbed.setSelectedComponent(c1);
        c2.JtCliente.requestFocus();
        c1.JtCliente.requestFocus();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabbed;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
